django_app/urls.py
from django.contrib import admin
from django.urls import path,include
import hello.views as hello
from django .views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/',include('hello.urls',namespace='hello')),
]

hello/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django .views.generic import TemplateView



app_name = 'sampleapp'

urlpatterns = [
        path('login/', LoginView.as_view(template_name = 'hello/login.html'), name="login"),
        path('logout/',LogoutView.as_view(template_name = 'hello/logout.html'), name="logout"),
        path('', views.MonthCalendar.as_view(), name='month'),
        path('index', views.index,name='index'),
        path('index/<int:year>/<int:month>/<int:day>', views.index, name='index'),
        path('create/<int:year>/<int:month>/<int:day>',views.create,name='create'),
        path('month/<int:year>/<int:month>', views.MonthCalendar.as_view(), name='month'),
        path ('signup',views.signup,name='signup'),
        path('edit/<int:num>/<int:year>/<int:month>/<int:day>',views.edit,name='edit'),
        path('delete/<int:num>/<int:year>/<int:month>/<int:day>',views.delete,name='delete'),
        path('search',views.search,name='search'),
        path('register/<int:num>/<int:year>/<int:month>/<int:day>',views.register,name='register'),
        path('cancel/<int:num>/<int:year>/<int:month>/<int:day>',views.cancel,name='cancel'),
        path(
        'month_with_schedule/',
        views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
        ),
        path(
        'month_with_schedule/<int:year>/<int:month>/',
        views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'
        ),
]

hello/models.py
import datetime
from django.db import models
from django.utils import timezone

subjects = [
            ('国語','国語'),
            ('数学','数学'),
            ('英語','英語'),
            ('理科','理科'),
            ('社会','社会')
        ]

times = [
    ('10:50','10:50'),
    ('12:50','12:50'),
    ('14:20','14:20'),
    ('15:50','15:50'),
    ('17:20','17:20'),
    ('18:50','18:50'),
    ('20:20','20:20'),
]

grades = [
    ('小1','小1'),
    ('小2','小2'),
    ('小3','小3'),
    ('小4','小4'),
    ('小5','小5'),
    ('小6','小6'),
    ('中1','中1'),
    ('中2','中2'),
    ('中3','中3'),
    ('高１','高１'),
    ('高2','高2'),
    ('高3','高3'),
]

class Users(models.Model):
    name=models.CharField(max_length=100)
    mail=models.EmailField(max_length=200)
    passward=models.CharField(max_length=100)
    

    def __str__(self):
        return self.name


class Classes(models.Model):
    date    = models.DateField()
    time    = models.TimeField(choices=times)
    name    = models.CharField(max_length=100)
    grade   = models.CharField(choices=grades,max_length=100)
    subject = models.CharField(choices=subjects,max_length=100)
    remark  = models.CharField(max_length=100)
    act_user = models.CharField(max_length=100)

    def __str__(self):
        return self.subject


class Act_person(models.Model):
    act_person_name = models.CharField(max_length=100)
    date = models.DateField()
    time = models.TimeField()

    def __str__(self):
        return self.act_person_name
    

class Schedule(models.Model):
    """スケジュール"""
    summary = models.CharField('概要', max_length=50)
    description = models.TextField('詳細な説明', blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7, 0, 0))
    end_time = models.TimeField('終了時間', default=datetime.time(7, 0, 0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.summary

hello/forms.py
from django import forms
from .models import Users,Classes,Act_person
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

class ClassesForm(forms.ModelForm):
    class Meta:
        model  = Classes
        fields = ['date','time','name','grade','subject','remark']
        widgets = {'act_user':forms.HiddenInput(),
            }

##バリデーション



class UsersForm(forms.Form):
    name     = forms.CharField(label='name')
    mail     = forms.EmailField(label='mail')
    passward = forms.CharField(label='passward')

class Act_personForm(forms.Form):
    act_person_name = forms.CharField(label='act_person_name')
    date            = forms.DateField(label='date')
    time            = forms.TimeField(label='time')

class PostForm(forms.Form):
    subject         = forms.CharField(max_length=100,widget=forms.Textarea)
    class Meta:
        model  = Classes
        fields = ['subject']

class SearchForm(forms.Form):
    search = forms.CharField(label='Search',required=False)




hello/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.shortcuts import redirect
from .forms import ClassesForm
from .models import Classes
from django.views import generic
from . import mixins
from .forms import SignUpForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django import forms
from . forms import SearchForm
from .models import Schedule




def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(to='/hello/')
    else:
        form = SignUpForm()
    return render(request, 'hello/signup.html', {'form': form})


@login_required(login_url='/hello/login/')
def index(request, year, month, day):
    data = Classes.objects.filter(date__year=year,date__month=month,date__day=day)
    #user_id = request.user.id
    params = {
             'title':'代行情報',
             'message':'代行要請',
             'msg':'top',
             'form':'Classesform',
             'data':data,
             'year':year,
             'month':month,
             'day':day,
             #'user_id':user_id
    }
    if (request.method == 'POST'):
        date = request.POST['date']
        time = request.POST['time']
        name = request.POST['name']
        grade = request.POST['grade']
        subject = request.POST['subject']
        remark = request.POST['remark']
        print(request.user.username)
        classes = Classes(date=date,time=time,name=name,\
                grade=grade,subject=subject,remark=remark,act_user=request.user.username)
        classes.save()
        year = str(year)
        month = str(month)
        day = str(day)
        return redirect(to='/hello/index/'+year+'/'+month+'/'+day)
    return render(request,'hello/index.html',params)

@login_required(login_url='/hello/login/')
def register(request,num,year,month,day):
    classes = Classes.objects.get(id=num)
    classes.act_user = request.user.username
    classes.save()
    year = str(year)
    month = str(month)
    day = str(day)
    return redirect(to='/hello/index/'+year+'/'+month+'/'+day)

@login_required(login_url='/hello/login/')
def cancel(request,num,year,month,day):
    classes = Classes.objects.get(id=num)
    classes.act_user = ""
    classes.save()
    year = str(year)
    month = str(month)
    day = str(day)
    return redirect(to='/hello/index/'+year+'/'+month+'/'+day)




@login_required(login_url='/hello/login/')
def create(request,year,month,day):
    if (request.method == 'POST'):
        date = request.POST['date']
        time = request.POST['time']
        name = request.POST['name']
        grade = request.POST['grade']
        subject = request.POST['subject']
        remark = request.POST['remark']
        classes = Classes(date=date,time=time,name=name,\
                 grade=grade,subject=subject,remark=remark)
        classes.save()
        year = str(year)
        month = str(month)
        day = str(day)
        return redirect(to='/hello/index/'+year+'/'+month+'/'+day)
    data = Classes.objects.filter()

    classform = ClassesForm()
    classform.fields["date"] = forms.DateField(initial=str(year) + '-' + str(month) + '-' + str(day))

    params = {
        'title':'代行要請',
        'message':'top',
        'msg':'前に戻る',
        'form':classform,
        'data':data,
        'year':year,
        'month':month,
        'day':day,
    }
    print(classform)
    
    return render(request,'hello/create.html',params)

@login_required(login_url='/hello/login/')
def edit(request,num,year,month,day):
    data = Classes.objects.get(id=num)
    if (request.method == 'POST'):
        classes = ClassesForm(request.POST,instance=data)
        #classes.act_user = request.user.username
        classes.save()
        year = str(year)
        month = str(month)
        day = str(day)
        return redirect(to='/hello/index/'+year+'/'+month+'/'+day)
    params = {
        'title': '代行要請',
        'messege':'top',
        'msg':'前に戻る',
        'form':ClassesForm(instance=data),
        'id':num,
        'year':year,
        'month':month,
        'day':day,
    }
    return render(request,'hello/edit.html',params)

@login_required(login_url='/hello/login/')
def delete(request,num,year,month,day):
    classes = Classes.objects.get(id=num)
    if (request.method == 'POST'):
        classes.delete()
        year = str(year)
        month = str(month)
        day = str(day)
        return redirect(to='/hello/index/'+year+'/'+month+'/'+day)
    params = {
        'title':'代行要請削除',
        'messege':'top',
        'msg':'前に戻る',
        'id':num,
        'data':classes,
        'year':year,
        'month':month,
        'day':day,
    }
    return render(request,'hello/delete.html',params)

@login_required(login_url='/hello/login/')
def search(request):
    if (request.method == 'POST'):
        msg = '調べたい日付をYYYY-MM-DD形式で検索してください。'
        form = SearchForm(request.POST)
        str = request.POST['search']
        data = Classes.objects.filter(date=str)
    else:
        msg = '調べたい日付をYYYY-MM-DD形式で検索してください。'
        form = SearchForm()
        data = Classes.objects.all()
    params = {
        'title':'代行要請日の検索',
        'message':msg,
        'form':form,
        'data':data,
    }
    return render(request,'hello/search.html',params)






class MonthCalendar(LoginRequiredMixin,mixins.MonthCalendarMixin, generic.TemplateView):
    login_url = '/login/'
    """月間カレンダーを表示するビュー"""
    template_name = 'hello/month.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context


class MonthWithScheduleCalendar(mixins.MonthWithScheduleMixin, generic.TemplateView):
    login_url = '/login/'
    """スケジュール付きの月間カレンダーを表示するビュー"""
    template_name = 'hello/month_with_schedule.html'
    model = Classes
    date_field = 'date'
    data = Classes.objects.all()

    def get_context_data(self,year,month,**kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        context['data'] = Classes.objects.filter(date__year=year,date__month=month)
        return context


hello/templates/hello/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>カレンダー</title>
</head>
<body>

<div class="container" mt-3>
    {% block content %}{% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
{% block extrajs %}{% endblock %}
</body>
</html>

hello/templates/hello/create.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css"
        href="{% static 'hello/css/style.css' %}" />
</head>
<body>
    <h1>{{title}}</h1>
    <p><a href="{% url 'hello:month' %}">{{message|safe}}</a></p>
    <p><a href="{% url 'hello:index' year month day %}">{{msg|safe}}</a></p>
    <p>選択した日は{{year}}/{{month}}/{{day}}です。</p>
    <table>
        <form action="{% url 'hello:create' year month day %}" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <tr><td></td><td><input type="submit" value="click"></td></tr>
        </form>
    </table>
</body>
</html>

hello/templates/hello/delete.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta chardet="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css"
        href="{% static 'hello/css/style.css' %}" />
</head>
<body>
    <h1>{{title}}</h1>
    <p><a href="{% url 'hello:month' %}">{{message|safe}}</a></p>
    <p><a href="{% url 'hello:index' year month day %}">{{msg|safe}}</a></p>
    <p>以下のレコードを削除します。</p>
    <table>
        <tr><th>DATE</th><td>{{data.date}}</td></tr>
        <tr><th>TIME</th><td>{{data.time}}</td></tr>
        <tr><th>NAME</th><td>{{data.name}}</td></tr>
        <tr><th>GRADE</th><td>{{data.grade}}</td></tr>
        <tr><th>SUBJECT</th><td>{{data.subject}}</td></tr>
        <tr><th>REMARK</th><td>{{data.remark}}</td></tr>
        <form action="{% url 'hello:delete' id year month day %}" method="post">
        {% csrf_token %}
        <tr><th></th><td><input type="submit" value="ok"></td></tr>
        </form>
    </table>
</body>
</html>

hello/templates/hello/edit.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css"
        href="{% static 'hello/css/style.css' %}" />
</head>
<body>
    <h1>{{title}}</h1>
    <p><a href="{% url 'hello:month' %}">{{message|safe}}</a></p>
    <p><a href="{% url 'hello:index' year month day %}">{{msg|safe}}</a></p>
    <p>日付はYYYY-MM-DD形式、時間はHH:MM形式で入力してください。</p>
    <table>
        <form action="{% url 'hello:edit' id year month day %}" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <tr><td></td><td><input type="submit" value=click></td></tr>
        </form>
    </table>
</body>
</html>

hello/templates/hello/index.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css"
        href="{% static 'hello/css/style.css' %}" />
</head>
<body>
    <h1>{{title}}</h1>
    <P><a href="{% url 'hello:create' year month day %}">{{message|safe}}</a></P>
    <p><a href="{% url 'hello:month' %}">{{msg|safe}}</a></p>
    <table>
        <tr>
            <th>DATE</th>
            <th>TIME</th>
            <th>NAME</th>
            <th>GRADE</th>
            <th>SUBJECT</th>
            <th>REMARK</th>
            <th>ACT_PERSON</th>
        </tr>
    {% for item in data %}
        <tr>
            <td>{{item.date}}</td>
            <td>{{item.time}}</td>
            <td>{{item.name}}</td>
            <td>{{item.grade}}</td>
            <td>{{item.subject}}</td>
            <td>{{item.remark}}</td>
            <td>{% if item.act_user == '' %}
                    <form action="{% url 'hello:register' item.id year month day %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="代行する">
                    </form>
                  {% else %}
                  <form action="{% url 'hello:cancel' item.id year month day %}" method="post">
                    {% csrf_token %}
                    {{item.act_user}} <input type="submit" value="キャンセルする">
                    </form>
                {% endif %}
            </td>
            <td><a href="{% url 'hello:edit' item.id year month day %}">Edit</a></td>
            <td><a href="{% url 'hello:delete' item.id year month day %}">Delete</a></td>
        </tr>
    {% endfor %}
    </table>
</body>
</html>

hello/templates/hello/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>LOGIN</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">ログイン</button>
        <p><a href="{% url 'hello:signup'  %}">ユーザー作成</a></p>
    </form>
</body>
</html>

hello/templates/hello/logout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>LOGOUT</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<form action="" method="POST">
{% csrf_token %}
<button type="submit">ログアウト</button>
</form>
</body>
</html>

hello/templates/hello/month.html
{% extends 'hello/base.html' %}

{% block content %}
    <a href="{% url 'hello:month' month_previous.year month_previous.month %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'hello:month' month_next.year month_next.month %}">次月</a>

    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week in month_days %}
            <tr>
                {% for day in week %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                {% if month_current.month == day.month %}
                    <a href="{% url 'hello:index' day.year day.month day.day %}">{{ day.day }}</a>
                {% endif %}

                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <table>
        <body>
            <p>代行要請のある日はこちらで調べられます。</p>
            <p><a href="{% url 'hello:search' %}">検索</a></p>
            <a href="{% url 'hello:logout' %}">ログアウト</a>
        </body>
    </table>
{% endblock %}

hello/templates/hello/month_with schedule.html
{% extends 'hello/base.html' %}
{% block content %}
    <style>
        table {
            table-layout: fixed;
        }

        td > div {
            height: 100px;
            overflow: hidden;
            white-space: nowrap;
        }

    </style>
    <a href="{% url 'hello:month_with_schedule' month_previous.year month_previous.month %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'hello:month_with_schedule' month_next.year month_next.month %}">次月</a>
    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week_day_schedles in month_day_schedules %}
            <tr>
                {% for day, schedules in week_day_schedles.items %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                <div>
                    {% if month_current.month != day.month %}
                        {{ day | date:"m/d" }}
                    {% else %}
                        {{ day.day }}
                    {% endif %}

                    {% for schedule in schedules %}
                        <p>{{ schedule.summary }}</p>
                    {% endfor %}
                </div>
                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

hello/templates/hello/month_with_schedule.html
{% extends 'hello/base.html' %}
{% block content %}
    <style>
        table {
            table-layout: fixed;
        }

        td > div {
            height: 100px;
            overflow: hidden;
            white-space: nowrap;
        }

    </style>
    <a href="{% url 'hello:month_with_schedule' month_previous.year month_previous.month %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'hello:month_with_schedule' month_next.year month_next.month %}">次月</a>
    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week_day_schedles in month_day_schedules %}
            <tr>
                {% for day, schedules in week_day_schedles.items %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                <div>
                    {% if month_current.month != day.month %}
                        {{ day | date:"m/d" }}
                    {% else %}
                        <a href="{% url 'hello:index' day.year day.month day.day %}">{{ day.day }}</a>
                    {% endif %}

                    {% for item in data %}
                    <tr></tr> 
                        
                            <td>{{item.time}}</td>
                            <td>{{item.grade}}</td>
                            <td>{{item.subject}}</td>
                    {% endfor %}
                </div>
                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

hello/templates/hello/search.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css"
        href="{% static 'hello/css/style.css' %}"/>
</head>
<body>
    <h1>{{title}}</h1>
    <p><a href="{% url 'hello:month' %}">top</a></p>
    <p>{{message|safe}}</p>
    <table>
        <form action="{% url 'hello:search' %}" method="post">
        {% csrf_token %}
        {{form}}
        <tr><th></th><td><input type="submit" value="click"></td></tr>
        </form>
    </table>
    <hr>
    <table>
        <tr>
            <th>DATE</th>
            <th>TIME</th>
            <th>NAME</th>
            <th>GRADE</th>
            <th>SUBJECT</th>
            <th>REMARK</th>
            <th>ACT_USER</th>
        </tr>
    {% for item in data %}
        <tr>
            <td>{{item.date}}</td>
            <td>{{item.time}}</td>
            <td>{{item.name}}</td>
            <td>{{item.grade}}</td>
            <td>{{item.subject}}</td>
            <td>{{item.remark}}</td>
            <td>{% if item.act_user == '' %}
                    <form action="{% url 'hello:register' item.id item.date.year item.date.month item.date.day  %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="代行する">
                    </form>
                  {% else %}
                   <form action="{% url 'hello:cancel' item.id item.date.year item.date.month item.date.day %}" method="post">
                    {% csrf_token %}
                    {{item.act_user}} <input type="submit" value="キャンセルする">
                    </form>
                {% endif %}
            </td>
    {% endfor %}     
    </table>
</body>
</html>

hello/templates/hello/signup.html
{% load static %}
<div class="container">
    <p></p>
    <h2>ユーザ登録</h2>
    <p>塾代行アプリの利用にはユーザー登録をしてください。</p>
    <p>パスワードは４文字以上にして下さい。</p>
</div>

<div class="py-3">
    <div class="container">
        <!-- フォーム -->
        <form action="{% url 'hello:signup' %}" method="post">

            <!-- ユーザ名 -->
            <div class="form-group row">
                <label for="name" class="col-md-3 col-form-label">
                    ユーザ名 <span class="badge badge-warning">必須</span>
                </label>
                <div class="col-md-9">
                    {% csrf_token %}
                    {{ form.username }}
                </div>
            </div>
            <!-- /ユーザ名 -->

            <!-- パスワード -->
            <div class="form-group row">
                <label for="password" class="col-md-3 col-form-label">
                    パスワード <span class="badge badge-warning">必須</span>
                </label>
                <div class="col-md-9">
                    {% csrf_token %}
                    {{ form.password1 }}
                </div>
            </div>
            <!-- /パスワード -->

            <!-- パスワード確認 -->
            <div class="form-group row">
                <label for="password2" class="col-md-3 col-form-label">
                    パスワードの確認 <span class="badge badge-warning">必須</span>
                </label>
                <div class="col-md-9">
                    {% csrf_token %}
                    {{ form.password2 }}
                </div>
            </div>
            <!-- /パスワード確認 -->

            {# エラーメッセージを表示 #}
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                 {% endfor %}
            {% endif %}

            <!-- 確認ボタン -->
            <div class="form-group row justify-content-end">
                <div class="col-md-9">
                    <button type="submit" class="btn btn-primary">登録する</button>
                </div>
            </div>

        </form>
        <!-- /フォーム -->
    </div>
</div>

hello/templates/hello/site_base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>MicroBlog</title>
  </head>
  <body>
  <h1>MicroBlog</h1>
  <div>
  {% block body %}{% endblock %}
  </div>
  </body>
</html>

hello/templates/hello/taking_over.html
{% load static %}